meta_product_name: "Marién Yoga"
meta_title: "Marién Yoga - Bienestar y salud"
meta_description: "Aprende a meditar, Conecta con tu cuerpo, Calma tu mente"
meta_image: "meta_image.jpg" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
