meta_product_name: "Marién Yoga"
meta_title: "Marién Yoga - Bienestar y salud"
meta_description: "Relevant description"
meta_image: "profil.jpg" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
