meta_product_name: "Marién Yoga"
meta_title: "Marién Yoga - Bienestar y salud"
meta_description: "Barcelona | yoga hatha | nidra yoga | Encuentra tu bienestar y equilibrio
 | Yoga para una vida sana
 | Mente y cuerpo sanos
 | Expande tu consciencia
 | Simplifica tu vida, menos es más
 | Aprendre a meditar
 | Diseña tu autopractica
 | El yoga es para todos
 | Practica conmigoAprende a meditar, Conecta con tu cuerpo, Calma tu mente"
meta_image: "meta_image.jpg" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
